# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-29 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20170711_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='image',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
